language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script:
  - sbt clean coverage test
after_success:
  - git config --global user.name "travisbot"
  - git config --global user.email "support@travis-ci.org"
  - git config --global push.default simple
  - sbt coveralls
  -
  >
    echo $TRAVIS_BRANCH; echo $TRAVIS_PULL_REQUEST; echo $TRAVIS_JDK_VERSION;
    if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_JDK_VERSION == 'oraclejdk8' ]]; then
      sbt ghpages-push-site
    fi
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
