language: scala
scala:
  - 2.12.0
  - 2.11.8
  - 2.10.6
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
matrix:
  exclude:
  - scala: 2.12.0
    jdk: oraclejdk7
  - scala: 2.12.0
    jdk: openjdk7
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - git config --global user.name "travisbot"
  - git config --global user.email "support@travis-ci.org"
  - git config --global push.default simple
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
  -
  >
    if [[ $TRAVIS_BRANCH == 'master' && \
          $TRAVIS_PULL_REQUEST == 'false' && \
          $TRAVIS_JDK_VERSION == 'oraclejdk8' && \
          $TRAVIS_SCALA_VERSION == "2.12.0" ]]; then
      export SBT_GHPAGES_COMMIT_MESSAGE="Auto-update site ($TRAVIS_COMMIT)"
      sbt ++$TRAVIS_SCALA_VERSION ghpages-push-site
    fi
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
